### ISSUE TITLE
Stop the time before the countdown ends

### ISSUE THREAD

**Issue by ardcarvalho** [caiomts/timerdo#10] opened 2021-12-07 13:46 UTC
Talking about functionalities, is it possible to stop the timer (countdown) before its ending?
I've set 10 minutes to a task but I finished before it (efficiency is my last name). How can I start the timer?

**Comment by caiomts** [comment] 2021-12-07 14:42
Duplicate of #3

**Closed by caiomts** 2021-12-07 14:42 UTC
